### ISSUE TITLE
Define `prerelease` and `release` workflows from the same steps.

### ISSUE THREAD

**Issue by dbanty** [knope-dev/knope#241]
A common pattern is to have two workflows that are identical except that the `PrepareRelease` step in one version has a `prerelease_label` and the other does not.

It would be much more convenient for someone to define a `release` workflow, and simply toggle on a `prerelease_label` whenever they want to—rather than having an almost-duplicate workflow.

## Ideas

1. Have a `prerelease_option` field for `PrepareRelease` to allow the user to define a custom command line option which, when set, will trigger a prerelease. For example, if `prerelease_option = "prerelease"`, the `knope release --prerelease=rc` will work the same as if `prerelease_label = "rc"` at been set.
2. _Always_ define a `--prerelease-label` command line option that, when provided, will alter any `PrepareRelease` step to include the passed-in label. This would supersede `prerelease_label` as well to allow folks to override a default (e.g., they normally use `rc` but today they want `beta`).
3. Read a `KNOPE_PRERELEASE_LABEL` environment variable which has the same effect as 2.

Feedback on which of these options is the best would be appreciated!

**Comment by Shadow53** [comment]
I think the following would be good:

- Accept both an environment variable and a command flag
- If the flag or variable is set without an associated value, use whatever is defined in `knope.toml`. Otherwise, use the associated value.
- I like `--prerelease[=name]` and `KNOPE_PRERELEASE=[name]`

For clarity, I see this following something like this set of rules for the associated value:
- enable prerelease, use default from config: --prerelease`, `--prerelease=<truthy>`, `KNOPE_PRERELEASE=` (empty, not unset), `KNOPE_PRERELEASE=<truthy>`
- disable prerelease if otherwise enabled: `--no-prerelease`, `--prerelease=<falsey>`, `KNOPE_PRERELEASE=<falsey>`
- enable prerelease with name override: same as enable, but use non-truthy-or-falsey values only (value must be provided)

Alternatively, whatever support `clap` has for this sort of thing is probably good too.

**Comment by dbanty** [comment]
I don't want to take away the ability to have workflows that are explicitly/exclusively prerelease, which it sounds like that would do. I also would like to avoid breaking changes/churn unless super necessary.

So, all things equal, a `PrepareRelease` step with `prerelease_label` set should still create a pre-release. Meaning the empty `--prerelease` or `KNOPE_PRERELEASE` would not have any effect. I think that also limits the utility of `--no-prerelease` as it would only work if the default workflow was creating a prerelease and the user had to opt out to create a full release. Typically (as far as I've seen), prereleases are much rarer, so that feels backward.

I like the idea of accepting both the variable and the flag, though, to give more options to folks (e.g., in CI).
