### ISSUE TITLE
Consider "too new" prerelease tags when bumping.

### ISSUE THREAD

**Issue by Shadow53** [knope-dev/knope#334]
This is a follow-up to #322.

In rigetti/quil-rs, we have the following situation:

- Latest stable is `0.14.2`
- Latest prerelease *since* latest stable does not exist.
- *Newest* prerelease before latest stable is `0.14.2-rc.0`
- Before that was `0.10.0-rc.1` (due to previous bug)
- The *largest* prerelease is from even earlier: `0.15.0-rc.0`

We want to avoid the eventual problem of adding a breaking change that would bump us back to `0.15.0-rc.0`. Currently, running the `knope` prerelease flow with `--dry-run` indicates that it would try to bump to this version that already exists.

I think the safest option is for `knope` to bump the latest prerelease if it is newer than the latest stable, *even if* it is newer than the version that the latest stable would bump to. That is, for our situation:

- "Correct" (previous) bump: `0.14.3-rc.0`
- "Fixed" (new) bump: `0.15.0-rc.1`

**Comment by Shadow53** [comment]
I've opened a PR for this, but I am open to discussion about implementation and whether/how this should be addressed, if not how I implemented it.

**Comment by dbanty** [comment]
I think the current behavior is more correct—the prerelease should always be the version the project will be when released—but with a prerelease component appended.

For example—I want to ensure we retain the case where the semantic version of the next release increases, which should result in the next prerelease increasing the primary components. So:

1. You're on 1.2.3
2. You add a `fix:`
3. You release 1.2.4-rc.0
4. You add a `feat:`
5. The next prerelease should be `1.3.0-rc.0` since the next full version will be `1.3.0`

More specific to your case—if the next version will be 0.14.3, you should not release a `0.15.0-rc.1` in advance of it. A semver project _should_ only ever increase in version from a given point, so I assume the `v0.15.0-rc.0` tag is a mistake? In which case, shouldn't you delete the tag so that the versions stay correct?

Please tell me if I'm misunderstanding the issue here.

---

There is another case to consider—which, I don't think Knope covers yet. There is often the case where two major versions need to be maintained—say you've released `3.5.0` and are continuing to develop new features, but still need to support `2.7.41` (yes, this is a Python reference). If you switch to the `v2` branch and add a `fix: yet another security issue`, you should be able to release `2.7.42-rc.0` and eventually `2.7.42` on that branch. I'm not sure how the current code would handle that—would it find the newer 3.x tags and have a fit?

**Comment by Shadow53** [comment]
>  A semver project should only ever increase in version from a given point, so I assume the v0.15.0-rc.0 tag is a mistake? In which case, shouldn't you delete the tag so that the versions stay correct?

The tag *was* a mistake, AFAICT, but was actually released, including to [crates.io](https://crates.io/crates/quil-rs/0.15.0-rc.0). So even if we delete the GitHub tag/release pair, we'll still have issues when `knope` decides we're due for a minor version bump.

Regardless of how it is handled, the desired outcome is that `knope` does not try to create a (pre)release that already exists, even if it was created in error. So, *at some point*, and in our particular case, it should jump from `0.14.x` to `0.15.0-rc.1`, skipping `rc.0`, since it already exists.

**Comment by dbanty** [comment]
Hm… so maybe the answer should be that instead of finding the latest prerelease, then deciding whether or not to use it, we calculate the next release, then see if there has already been a prerelease for it?

To save some cycles re-reading all the git tags, we could pull out _all_ of the prerelease tags after the current stable, and pass those to the method that calculates the next prerelease 🤔
