### ISSUE TITLE
bug: Character escape inside `knope.toml:workflows.steps.command` doesn't parse correctly

### ISSUE THREAD

**Issue by alex-way** [knope-dev/knope#918]
Not quite sure what's happening here but with the default generated `knope.toml` file I'm getting an error when running knope release:

```toml
#Knope.toml
[package]
versioned_files = ["package.json"]
changelog = "CHANGELOG.md"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\" && git push"

[workflows.steps.variables]
"$version" = "Version"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "alex-way"
repo = "test-repo"

```

```
error: pathspec 'prepare' did not match any file(s) known to git
error: pathspec 'release' did not match any file(s) known to git
error: pathspec '3.0.4\"' did not match any file(s) known to git
Error:   × Problem with workflow release

Error: command::failed

  × Command returned non-zero exit code
  help: The command failed to execute. Try running it manually to get more information.
```

This may be a windows-specific issue, but I'll try to investigate further and submit a bug fix if possible.

**Comment by dbanty** [comment]
There's probably a Windows compatibility issue of some sort. I started adding in tests on Windows in #919, I need to work out some of the normal inconsistencies to narrow down to the real problem, but I did see some some output similar to what you mention above.

I have a Windows machine for testing, it's just been a minute since I used it 😅. I'll dust it off this weekend and get it all smoothed out. Thanks for the report, and sorry you're bumping into issues so soon!

**Comment by dbanty** [comment]
Okay, this is definitely an issue with upstream command runners, and I haven't found one yet that doesn't have the issue 😅. I'm asking the maintainer of the most popular one what the best approach is over in https://github.com/hniksic/rust-subprocess/issues/27, so hopefully that gets us a solution.

Adding tests for Windows in #919 has revealed at least one other bug, though, that's now fixed!

**Comment by dbanty** [comment]
This should be fixed now!
